on: [push]

name: Mystery Workflow 🤔

jobs:
  mystery:
    runs-on: ubuntu-latest
    name: Mystery Job
    steps:

    # First check the repo out
    - name: Checkout
      uses: actions/checkout@v2

    # Setup node
    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    # Now get the color
    - name: Get Color
      id: get-color
      run: |
        COLOR=$(node -p "require('./color.js')")
        echo "::set-output name=COLOR::${COLOR}"

    - name: Top Secret Mystery Action Step
      uses: mtharrison/top-secret-mystery-action@v0.1.1
      with:
        color: ${{ steps.get-color.outputs.COLOR }}
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        USERNAME: ${{ secrets.USERNAME }}

    # - name: Hello world action step
    #   id: hello
    #   uses: actions/hello-world-javascript-action@v1.1
    #   with:
    #     who-to-greet: 'Mona the Octocat'
    # # Use the output from the `hello` step
    # - name: Get the output time
    #   run: echo "The time was ${{ steps.hello.outputs.time }}"
